modLoader="javafml"
loaderVersion="[45,)"
license="Academic Free License v3.0"

[[mods]]
modId="moe"
version="0.0.6"
displayName="Mod Of Everything By Bufka2011"
credits="Bufka2011, GameRuBe, MCreator"
displayURL="https://mcreator.net"
authors="PARADISE team, MCreator"
description="MC Mod Of Everything."

[[dependencies.moe]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"




